### ISSUE TITLE
Fraola

### ISSUE THREAD

**Issue by mindplay-dk** [iDoRecall/comparisons#1]
Not on your list, maybe because it's a commercial editor, but this is really the most well-behaved editor I've seen so far - like for one, I was able to paste from my local clipboard on Win10:

https://www.froala.com/wysiwyg-editor

Thought I'd mention it, as this is my own personal top contender at the moment, and it sounds like being able to paste was an important requirement for you.

Thanks for sharing your list! This gave me a lot of useful things to go on :-)

**Comment by dandv** [comment]
Froala is actually #1 in the [list of editors that can't paste formatted text properly](https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md#cant-paste-images-or-rich-text) :)

**Comment by mindplay-dk** [comment]
Have you re-tested that in the latest version? 

Have you asked the developers about it? They have been very responsive to my questions so far.

What's your sample content and your criteria for correctness when evaluating this feature?

**Comment by dandv** [comment]
I assume you hadn't found Froala due to the misspelling ("Fraola").

As you can see from the link in my first comment on this issue, I did ask the developers, at https://github.com/froala/wysiwyg-editor/issues/552. Incidentally, they're also fellow Romanians, so if anything, I would've been biased *for* Froala.

The testing criteria are also in the comparison file. Here, I'll do the work for you :)

![image](https://cloud.githubusercontent.com/assets/33569/12809017/7276b412-cad0-11e5-9ad0-7814d024f73d.png)

**Comment by mindplay-dk** [comment]
I've tried pasting from StackOverflow, from "JavaScript Patterns", from a Google Doc, from WordPad (yikes) and from various other HTML pages - it does what I expect and want, but I suppose it all depends on what you expect.

The only undesirable effect I noticed, was garbage (empty) `<code></code>` tags, which could have been stripped - but I guess there's no real way to know if you should or shouldn't strip empty tags, since they might actually display. Dunno. Pasting in version 2 works to my satisfaction :-)
